import { useCallback, useEffect, useRef, useState } from 'react';
import { useNodesState, useEdgesState, type NodeMouseHandler } from '@xyflow/react';
import { useUndoRedo } from './hooks/useUndoRedo';
import { MetadataSection } from './MetadataSection';
import { TrainingPhraseEditor } from './TrainingPhraseEditor';
import { ActionBar } from './ActionBar';
import { FlowCanvas } from './FlowCanvas';
import { NodeConfigPanel } from './NodeConfigPanel';
import { stepsToFlow } from './utils/stepsToFlow';
import { flowToSteps } from './utils/flowToSteps';
import { applyLayout } from './utils/autoLayout';
import type { Scenario, ScriptInfo } from '../../types/scenario';
import type { FlowNode, FlowEdge, FlowNodeData } from '../../types/flowTypes';
import { v4 as uuidv4 } from 'uuid';
import './FlowEditor.css';

interface Props {
  scenario: Scenario;
  onChange: (s: Scenario) => void;
  scripts: ScriptInfo[];
  isNew: boolean;
  onSave: (s: Scenario, andTrain: boolean) => void;
  onDelete: (id: string) => void;
  saving: boolean;
  saveResult: { ok: boolean; message: string } | null;
}

const DEFAULT_NODE_DATA: Record<string, FlowNodeData> = {
  run_script: { nodeType: 'run_script' },
  ask_choice: { nodeType: 'ask_choice', options: [] },
  ask_input: { nodeType: 'ask_input' },
  end: { nodeType: 'end' },
  goto: { nodeType: 'goto' },
};

export function FlowEditor({ scenario, onChange, scripts, isNew, onSave, onDelete, saving, saveResult }: Props) {
  const [nodes, setNodes, onNodesChange] = useNodesState<FlowNode>([]);
  const [edges, setEdges, onEdgesChange] = useEdgesState<FlowEdge>([]);
  const [selectedNodeId, setSelectedNodeId] = useState<string | null>(null);
  const [expanded, setExpanded] = useState(false);

  // Refs to always get current nodes/edges (for undo snapshots)
  const nodesRef = useRef(nodes);
  nodesRef.current = nodes;
  const edgesRef = useRef(edges);
  edgesRef.current = edges;

  const getNodes = useCallback(() => nodesRef.current, []);
  const getEdges = useCallback(() => edgesRef.current, []);
  const { takeSnapshot, undo, redo } = useUndoRedo(getNodes, getEdges, setNodes, setEdges);

  // Ctrl+Z / Ctrl+Shift+Z keyboard shortcut
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === 'z') {
        e.preventDefault();
        if (e.shiftKey) redo();
        else undo();
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [undo, redo]);

  // localStorage key for persisting layout
  const layoutKey = `flow-layout-${scenario.id}`;

  // Re-initialize canvas only when the scenario ID changes (not on metadata edits)
  useEffect(() => {
    const { nodes: rawNodes, edges: rawEdges } = stepsToFlow(scenario.steps);

    // Try to restore saved layout from localStorage
    try {
      const saved = localStorage.getItem(`flow-layout-${scenario.id}`);
      if (saved) {
        const layout = JSON.parse(saved) as {
          positions: Record<string, { x: number; y: number }>;
          bendPoints: Record<string, unknown>;
          extraEdges?: FlowEdge[];
        };
        // Apply saved positions to nodes
        for (const node of rawNodes) {
          if (layout.positions[node.id]) {
            node.position = layout.positions[node.id];
          }
        }
        // Apply saved bend points to edges from steps
        for (const edge of rawEdges) {
          if (layout.bendPoints[edge.id]) {
            edge.data = { ...edge.data, bendPoints: layout.bendPoints[edge.id] };
          }
        }
        // Restore extra edges (user-drawn connections not in YAML)
        const nodeIds = new Set(rawNodes.map(n => n.id));
        const edgeIds = new Set(rawEdges.map(e => e.id));
        const validExtras = (layout.extraEdges ?? []).filter(
          e => nodeIds.has(e.source) && nodeIds.has(e.target) && !edgeIds.has(e.id)
        );
        setNodes(rawNodes);
        setEdges([...rawEdges, ...validExtras]);
        setSelectedNodeId(null);
        return;
      }
    } catch { /* ignore parse errors, fall through to auto-layout */ }

    const laidOut = applyLayout(rawNodes, rawEdges);
    setNodes(laidOut);
    setEdges(rawEdges);
    setSelectedNodeId(null);
  }, [scenario.id]); // eslint-disable-line react-hooks/exhaustive-deps

  // Auto-save layout to localStorage (debounced)
  const saveTimer = useRef<ReturnType<typeof setTimeout>>();
  useEffect(() => {
    if (!scenario.id) return;
    clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(() => {
      const positions: Record<string, { x: number; y: number }> = {};
      for (const n of nodes) positions[n.id] = n.position;
      const bendPoints: Record<string, unknown> = {};
      for (const e of edges) {
        const bp = (e.data as Record<string, unknown>)?.bendPoints;
        if (bp) bendPoints[e.id] = bp;
      }
      // Find edges not generated by stepsToFlow (extra user-drawn connections)
      const { edges: baseEdges } = stepsToFlow(scenario.steps);
      const baseEdgeIds = new Set(baseEdges.map(e => e.id));
      const extraEdges = edges.filter(e => !baseEdgeIds.has(e.id));
      try {
        localStorage.setItem(layoutKey, JSON.stringify({ positions, bendPoints, extraEdges }));
      } catch { /* storage full — ignore */ }
    }, 500);
    return () => clearTimeout(saveTimer.current);
  }, [nodes, edges, scenario.id, layoutKey]);

  // Wrap node changes to snapshot once when drag starts
  const wasDragging = useRef(false);
  const handleNodesChange: typeof onNodesChange = useCallback((changes) => {
    const isDragging = changes.some((c) => c.type === 'position' && c.dragging);
    const hasRemove = changes.some((c) => c.type === 'remove');
    if (hasRemove) takeSnapshot();
    if (isDragging && !wasDragging.current) takeSnapshot();
    wasDragging.current = isDragging;
    onNodesChange(changes);
  }, [onNodesChange, takeSnapshot]);

  // Wrap edge changes to snapshot before edge removal
  const handleEdgesChange: typeof onEdgesChange = useCallback((changes) => {
    const hasRemove = changes.some((c) => c.type === 'remove');
    if (hasRemove) takeSnapshot();
    onEdgesChange(changes);
  }, [onEdgesChange, takeSnapshot]);

  // Wrap setEdges for connections (from FlowCanvas onConnect/onEdgesUpdate)
  const handleEdgesUpdate = useCallback((newEdges: FlowEdge[]) => {
    takeSnapshot();
    setEdges(newEdges);
  }, [takeSnapshot, setEdges]);

  const [localError, setLocalError] = useState<string | null>(null);

  const handleSave = (andTrain: boolean) => {
    setLocalError(null);
    const steps = flowToSteps(nodes, edges);
    if (steps.length === 0) {
      setLocalError('Cannot save: connect the Start node to at least one step node.');
      return;
    }
    if (!scenario.name.trim()) {
      setLocalError('Cannot save: scenario name is required.');
      return;
    }
    onSave({ ...scenario, steps }, andTrain);
  };

  const onNodeClick: NodeMouseHandler<FlowNode> = useCallback((_, node) => {
    setSelectedNodeId(node.id);
  }, []);

  const onPaneClick = useCallback(() => {
    setSelectedNodeId(null);
  }, []);

  const handleUpdateNode = useCallback((id: string, data: FlowNodeData) => {
    takeSnapshot();
    setNodes(nds => nds.map(n => n.id === id ? { ...n, data } : n));

    // Clean up edges for removed ask_choice options
    if (data.nodeType === 'ask_choice') {
      const validHandles = new Set((data.options ?? []).map((o: { value: string }) => `out-${o.value}`));
      setEdges(eds => eds.filter(e =>
        e.source !== id || validHandles.has(e.sourceHandle ?? '')
      ) as FlowEdge[]);
    }
  }, [takeSnapshot, setNodes, setEdges]);

  const handleDeleteNode = useCallback((id: string) => {
    takeSnapshot();
    setNodes(nds => nds.filter(n => n.id !== id));
    setEdges(eds => eds.filter(e => e.source !== id && e.target !== id) as FlowEdge[]);
    setSelectedNodeId(null);
  }, [takeSnapshot, setNodes, setEdges]);

  const handleAddNode = (type: string) => {
    takeSnapshot();
    const nodeId = uuidv4();
    const newNode: FlowNode = {
      id: nodeId,
      type,
      position: { x: 400 + Math.random() * 100 - 50, y: 300 + Math.random() * 100 - 50 },
      data: { ...(DEFAULT_NODE_DATA[type] ?? { nodeType: type as FlowNodeData['nodeType'] }) },
    };
    setNodes(nds => [...nds, newNode]);
    setSelectedNodeId(nodeId);
  };

  const selectedNode = nodes.find(n => n.id === selectedNodeId) ?? null;

  return (
    <div className="flow-editor-layout">
      <div className="flow-editor-top">
        <h2 className="form-title">{isNew ? 'Create New Scenario' : `Edit: ${scenario.name}`}</h2>
        <div className="flow-editor-top-sections">
          <MetadataSection scenario={scenario} onChange={onChange} />
          <TrainingPhraseEditor
            phrases={scenario.training_phrases}
            onChange={phrases => onChange({ ...scenario, training_phrases: phrases })}
          />
        </div>
      </div>

      {expanded && (
        <div className="flow-expanded-overlay">
          <div className="flow-expanded-header">
            <span className="flow-expanded-title">Flow Editor — {scenario.name || 'Untitled'}</span>
            <button className="btn-close-expanded" onClick={() => setExpanded(false)}>
              Close &times;
            </button>
          </div>
          <div className="flow-toolbar">
            <span className="flow-toolbar-label">Add Node:</span>
            {[
              { type: 'run_script', label: 'Run Script', color: '#3498db' },
              { type: 'ask_choice', label: 'Ask Choice', color: '#e67e22' },
              { type: 'ask_input', label: 'Ask Input', color: '#2ecc71' },
              { type: 'goto', label: 'Go To', color: '#9b59b6' },
              { type: 'end', label: 'End', color: '#e74c3c' },
            ].map(({ type, label, color }) => (
              <button
                key={type}
                className="btn-add-node"
                style={{ borderColor: color, color }}
                onClick={() => handleAddNode(type)}
              >
                + {label}
              </button>
            ))}
          </div>
          <div className="flow-expanded-canvas-area">
            <FlowCanvas
              nodes={nodes}
              edges={edges}
              onNodesChange={handleNodesChange}
              onEdgesChange={handleEdgesChange}
              onEdgesUpdate={handleEdgesUpdate}
              onNodeClick={onNodeClick}
              onPaneClick={onPaneClick}
            />
            <NodeConfigPanel
              node={selectedNode}
              scripts={scripts}
              onUpdateNode={handleUpdateNode}
              onDeleteNode={handleDeleteNode}
            />
          </div>
          <div className="flow-editor-bottom">
            {localError && <div className="flow-save-error">{localError}</div>}
            <ActionBar
              onSave={() => handleSave(false)}
              onSaveAndTrain={() => handleSave(true)}
              onDelete={isNew ? undefined : () => onDelete(scenario.id)}
              saving={saving}
              saveResult={saveResult}
            />
          </div>
        </div>
      )}

      <div className="flow-editor-body" style={expanded ? { visibility: 'hidden', height: 0, overflow: 'hidden' } : undefined}>
        <div className="flow-toolbar">
          <span className="flow-toolbar-label">Add Node:</span>
          {[
            { type: 'run_script', label: 'Run Script', color: '#3498db' },
            { type: 'ask_choice', label: 'Ask Choice', color: '#e67e22' },
            { type: 'ask_input', label: 'Ask Input', color: '#2ecc71' },
            { type: 'goto', label: 'Go To', color: '#9b59b6' },
            { type: 'end', label: 'End', color: '#e74c3c' },
          ].map(({ type, label, color }) => (
            <button
              key={type}
              className="btn-add-node"
              style={{ borderColor: color, color }}
              onClick={() => handleAddNode(type)}
            >
              + {label}
            </button>
          ))}
          <button className="btn-expand-canvas" onClick={() => setExpanded(true)}>
            Expand View
          </button>
          <span className="flow-toolbar-hint">
            Connect nodes by dragging from a handle ● to another node
          </span>
        </div>

        <div className="flow-editor-canvas-area">
          <FlowCanvas
            nodes={nodes}
            edges={edges}
            onNodesChange={onNodesChange}
            onEdgesChange={onEdgesChange}
            onEdgesUpdate={setEdges}
            onNodeClick={onNodeClick}
            onPaneClick={onPaneClick}
          />
          <NodeConfigPanel
            node={selectedNode}
            scripts={scripts}
            onUpdateNode={handleUpdateNode}
            onDeleteNode={handleDeleteNode}
          />
        </div>
      </div>

      <div className="flow-editor-bottom">
        <ActionBar
          onSave={() => handleSave(false)}
          onSaveAndTrain={() => handleSave(true)}
          onDelete={isNew ? undefined : () => onDelete(scenario.id)}
          saving={saving}
          saveResult={saveResult}
        />
      </div>
    </div>
  );
}
